///////////////////////////////////////////////////////////
//  CellRange.as
//  Macromedia ActionScript Implementation of the Class Range
//  Generated by Enterprise Architect
//  Created on:      22-һ��-2010 10:41:29
//  Original author: dengyang
///////////////////////////////////////////////////////////

package org.baicaix.editor {
	import org.baicaix.map.MapTile;
	import flash.display.BitmapData;
	import flexunit.framework.TestCase;
	import flexunit.framework.TestSuite;

	import org.baicaix.map.MapLayer;

	import flash.geom.Rectangle;

	/**
	 * @author dengyang
	 * @version 1.0
	 * @created 22-һ��-2010 10:41:29
	 */
	public class RangeTest extends TestCase {

		//------------------------------------
		// private, protected properties
		//------------------------------------
		
		private var _range : Range; 
		private var _sheet : Sheet;
		
		private var startX : int = 0;
		private var startY : int = 0;
		private var width : int = 3; 
		private var height : int = 4;

		//------------------------------------
		// public properties
		//------------------------------------
		

		//------------------------------------
		// constructor
		//------------------------------------
		
		public function RangeTest(methodName : String = null) {
			super.methodName = methodName;
		}

		//
		// PRIVATE, PROTECTED
		//________________________________________________________________________________________________
		


		// PUBLIC
		//________________________________________________________________________________________________
		
		override public function setUp():void{
	        super.setUp();
	        _sheet = new Sheet(new Editor(), new MapLayer());
	        _sheet.initCellsBySrc(new BitmapData(9999, 8888), -777);
	        _range = new Range();
	    }

	    override public function tearDown():void   {
	        super.tearDown();
	    }	
	    
		/**
		 * 選取區域
		 */
		public function testSelectRange() : void {
			//准备数据
			this._range.selectRange(_sheet, new Rectangle(startX, startY, width, height));
			//数量验证
			var time : int = 0;
			for each (var cell : Cell in _range.cells) {
				time++;
			}
			assertEquals(width*height, time);
			//数据验证
			assertEquals(this._range.sheet, _sheet);
//			var key : String = x + "," + y;
//			for (var x : int = startX;x < width + startX;x++) {
//				for (var y : int = startY; y < height + startY; y++) {
//					assertEquals(this._range.cells[key], this._sheet.cells[key]);
//				}
//			}
		}

		/**
		 * 查找上邊緣單元格
		 */
//		public function testFindTopCells() : void {
//			var topCells : Array = this._range.findTopCells();
//			assertEquals(topCells.length, width);
//			assertFalse(topCells.indexOf(new Cell(new Sheet(new Editor(), new MapLayer()), new MapTile())) > -1);
//			for (var x : int = 0; x < width; x++) {
//				assertTrue(topCells.indexOf(_range.cells[x + "," + startY]));
//			}
//		}

		/**
		 * 查找下邊緣單元格
		 */
		public function findBottomCells() : void {
		}
		
		/**
		 * 查找左邊緣單元格
		 */
		public function findLeftCells() : void {
		}
		
		/**
		 * 查找右邊緣單元格
		 */
		public function findRightCells() : void {
		}
		
		/**
		 * 顯示邊框
		 */
		public function showRim() : void {
		}
		
		/**
		 * 清除邊框
		 */
		public function clearRim() : void {
		}
		
		public function buildAllTest() : TestSuite {
			var suite : TestSuite = new TestSuite();  
			suite.addTest(new RangeTest("testSelectRange"));
			suite.addTest(new RangeTest("testFindTopCells"));
			return suite;
		}
	}//end Range
}