///////////////////////////////////////////////////////////
//  Sheet.as
//  Macromedia ActionScript Implementation of the Class Sheet
//  Generated by Enterprise Architect
//  Created on:      22-һ��-2010 10:41:35
//  Original author: dengyang
///////////////////////////////////////////////////////////

package org.baicaix.editor {
	import flexunit.framework.TestCase;

	/**
	 * @author dengyang
	 * @version 1.0
	 * @created 22-һ��-2010 10:41:35
	 */
	public class SheetTest extends TestCase {
		
		override public function setUp():void{
	        super.setUp();
	    }

	    override public function tearDown():void   {
	        super.tearDown();
	    }	
	}//end Sheet
}